import { Pedido } from "../../types/pedidos";

export const mockPedidos: Pedido[] = [
    {
        id: "PED001",
        data: new Date("2025-09-18T10:00:00"),
        cliente: "Ana Silva",
        marketplace: "Mercado Livre",
        idPlataforma: "ML8123456789",
        valor: 6999.99,
        status: "Pendente",
        subStatus: "Aguardando pagamento",
        tipoEnvio: "ML Envios",
        imagem: "/placeholder.svg",
        produto: "iPhone 15 Pro Max 256GB",
        sku: "IPH15PM-256",
        itens: [
            {
                id: "ITEM001",
                sku: "IPH15PM-256",
                nome: "iPhone 15 Pro Max 256GB",
                quantidade: 1,
                valor: 6999.99,
            },
        ],
    },
    {
        id: "PED002",
        data: new Date("2025-09-18T10:15:00"),
        cliente: "João Santos",
        marketplace: "Amazon",
        idPlataforma: "AMZ987654321",
        valor: 12999.99,
        status: "A vincular",
        subStatus: null,
        tipoEnvio: "Amazon Prime",
        imagem: "/placeholder.svg",
        produto: "MacBook Air M3 16GB 512GB",
        sku: "MBAIR-M3",
        itens: [
            {
                id: "ITEM002",
                sku: "MBAIR-M3",
                nome: "MacBook Air M3 16GB 512GB",
                quantidade: 1,
                valor: 12999.99,
            },
        ],
    },
    {
        id: "PED003",
        data: new Date("2025-09-18T10:20:00"),
        cliente: "Maria Oliveira",
        marketplace: "Shopee",
        idPlataforma: "SHP789123456",
        valor: 699.99,
        status: "Emissao NF",
        subStatus: "NF pendente",
        tipoEnvio: "Shopee Xpress",
        imagem: "/placeholder.svg",
        produto: "Samsung Galaxy S24 Ultra",
        sku: "SGS24U-256",
        itens: [
            {
                id: "ITEM003",
                sku: "SGS24U-256",
                nome: "Samsung Galaxy S24 Ultra",
                quantidade: 1,
                valor: 699.99,
            },
        ],
    },
    {
        id: "PED004",
        data: new Date("2025-09-18T10:30:00"),
        cliente: "Lucas Pereira",
        marketplace: "Magazine Luiza",
        idPlataforma: "MAG456789123",
        valor: 2299.99,
        status: "NF Emitida",
        subStatus: null,
        tipoEnvio: "Magalu Entrega",
        imagem: "/placeholder.svg",
        produto: "Nintendo Switch OLED",
        sku: "NSW-OLED",
        itens: [
            {
                id: "ITEM004",
                sku: "NSW-OLED",
                nome: "Nintendo Switch OLED",
                quantidade: 1,
                valor: 2299.99,
            },
        ],
    },
    {
        id: "PED005",
        data: new Date("2025-09-18T10:45:00"),
        cliente: "Fernanda Costa",
        marketplace: "Magazine Luiza",
        idPlataforma: "MAG1122334455",
        valor: 19.99,
        status: "Aguardando Coleta",
        subStatus: null,
        tipoEnvio: "Magalu Coleta",
        imagem: "/placeholder.svg",
        produto: "Cabo USB-C 2m",
        sku: "CBL-USBC-2M",
        itens: [
            {
                id: "ITEM005",
                sku: "CBL-USBC-2M",
                nome: "Cabo USB-C 2m",
                quantidade: 1,
                valor: 19.99,
            },
        ],
    },
    {
        id: "PED006",
        data: new Date("2025-09-18T11:00:00"),
        cliente: "Carlos Souza",
        marketplace: "Mercado Livre",
        idPlataforma: "ML5566778899",
        valor: 50.00,
        status: "Enviado",
        subStatus: "Em trânsito",
        tipoEnvio: "ML Envios",
        imagem: "/placeholder.svg",
        produto: "Kit 5x Panos de Limpeza Microfibra",
        sku: "KIT-PANO",
        itens: [
            {
                id: "ITEM006",
                sku: "KIT-PANO",
                nome: "Kit 5x Panos de Limpeza Microfibra",
                quantidade: 1,
                valor: 50.00,
            },
        ],
    },
    {
        id: "PED007",
        data: new Date("2025-09-18T11:30:00"),
        cliente: "Juliana Lima",
        marketplace: "Shopee",
        idPlataforma: "SHP9988776655",
        valor: 80.00,
        status: "Cancelado",
        subStatus: null,
        tipoEnvio: "Shopee Xpress",
        imagem: "/placeholder.svg",
        produto: "Fone de Ouvido sem Fio",
        sku: "FONE-BT",
        itens: [
            {
                id: "ITEM007",
                sku: "FONE-BT",
                nome: "Fone de Ouvido sem Fio",
                quantidade: 1,
                valor: 80.00,
            },
        ],
    },
    {
        id: "PED008",
        data: new Date("2025-09-18T11:45:00"),
        cliente: "Rafaela Mendes",
        marketplace: "Mercado Livre",
        idPlataforma: "ML1122334455",
        valor: 4500.00,
        status: "Pendente",
        subStatus: "Aguardando pagamento",
        tipoEnvio: "ML Envios",
        imagem: "/placeholder.svg",
        produto: "Smart TV 55 polegadas",
        sku: "SMARTTV-55",
        itens: [
            {
                id: "ITEM008",
                sku: "SMARTTV-55",
                nome: "Smart TV 55 polegadas",
                quantidade: 1,
                valor: 4500.00,
            },
        ],
    },
];
