create table if not exists public.marketplace_orders_presented_new (
  id uuid not null,
  organizations_id uuid null,
  company_id uuid null,
  marketplace text null,
  marketplace_order_id text null,
  status text null,
  status_detail text null,
  order_total numeric null,
  shipping_type text null,
  customer_name text null,
  id_buyer bigint null,
  first_name_buyer text null,
  last_name_buyer text null,
  shipping_city_name text null,
  shipping_state_name text null,
  shipping_state_uf text null,
  shipping_street_name text null,
  shipping_street_number text null,
  shipping_neighborhood_name text null,
  shipping_zip_code text null,
  shipping_comment text null,
  shipping_address_line text null,
  shipment_status text null,
  shipment_substatus text null,
  shipping_method_name text null,
  estimated_delivery_limit_at timestamp with time zone null,
  shipment_sla_status text null,
  shipment_sla_service text null,
  shipment_sla_expected_date timestamp with time zone null,
  shipment_sla_last_updated timestamp with time zone null,
  shipment_delays jsonb null,
  printed_label boolean null,
  printed_schedule timestamp with time zone null,
  payment_status text null,
  payment_total_paid_amount numeric null,
  payment_marketplace_fee numeric null,
  payment_shipping_cost numeric null,
  payment_date_created timestamp with time zone null,
  payment_date_approved timestamp with time zone null,
  payment_refunded_amount numeric null,
  items_count integer null,
  items_total_quantity integer null,
  items_total_amount numeric null,
  items_total_full_amount numeric null,
  items_total_sale_fee numeric null,
  items_currency_id text null,
  first_item_id text null,
  first_item_title text null,
  first_item_sku text null,
  first_item_variation_id bigint null,
  first_item_permalink text null,
  variation_color_names text[] null,
  category_ids text[] null,
  listing_type_ids text[] null,
  stock_node_ids text[] null,
  has_variations boolean null,
  has_bundle boolean null,
  has_kit boolean null,
  pack_id text null,
  label_cached boolean null,
  label_response_type text null,
  label_fetched_at timestamp with time zone null,
  label_size_bytes integer null,
  label_content_base64 text null,
  label_content_type text null,
  label_pdf_base64 text null,
  label_zpl2_base64 text null,
  unlinked_items_count integer null,
  has_unlinked_items boolean null,
  linked_products jsonb null,
  created_at timestamp with time zone null,
  last_updated timestamp with time zone null,
  last_synced_at timestamp with time zone null,
  status_interno text null,
  billing_doc_number text null,
  billing_doc_type text null,
  billing_email text null,
  billing_phone text null,
  billing_name text null,
  billing_state_registration text null,
  billing_taxpayer_type text null,
  billing_cust_type text null,
  billing_is_normalized boolean null,
  billing_address jsonb null,
  constraint marketplace_orders_presented_new_pkey primary key (id)
) TABLESPACE pg_default;
